import 'package:in_egypt_admin_panel/core/Entities/BookingEntity.dart';
import 'package:in_egypt_admin_panel/core/Entities/PlaceEntity.dart';
import 'package:in_egypt_admin_panel/core/helpers/getUserData.dart';
import 'package:in_egypt_admin_panel/features/Auth/domain/Entities/UserEntity.dart';

class Variables {
  static List<BookingEntity> testBookingsList = [
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        images: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        images: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        images: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        images: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      totalPrice: 100,
      status: "rejected",
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        images: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
  ];
  static List<PlaceEntity> testPlacesList = [
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      images: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
  ];
  static List<UserEntity> testUsers = [
    UserEntity(
      uid: 'u1',
      firstName: 'Dave',
      lastName: 'Smith',
      fullName: 'Dave Smith',
      email: 'dave.smith@example.com',
      phoneNumber: '01123456789',
      photoUrl: 'https://cdn-icons-png.flaticon.com/128/16683/16683419.png',
      role: 'Tourist',
      createdAt: '2024-06-01T10:30:00Z',
      isBlocked: false,
      isVerified: true,
    ),
    UserEntity(
      uid: 'u2',
      firstName: 'Sarah',
      fullName: 'Sarah Brown',
      lastName: 'Brown',
      email: 'sarah.brown@example.com',
      phoneNumber: '01234567890',
      photoUrl: 'https://cdn-icons-png.flaticon.com/128/16683/16683419.png',
      role: 'Guide',
      createdAt: '2024-06-10T15:45:00Z',
      isBlocked: false,
      isVerified: false,
    ),
    UserEntity(
      uid: 'u3',
      firstName: 'John',
      lastName: 'Doe',
      fullName: 'John Doe',
      email: 'john.doe@example.com',
      phoneNumber: '01098765432',
      photoUrl: 'https://cdn-icons-png.flaticon.com/128/16683/16683419.png',
      role: 'Tourist',
      createdAt: '2024-06-20T08:20:00Z',
      isBlocked: true,
      isVerified: true,
    ),
    UserEntity(
      uid: 'u4',
      firstName: 'Nour',
      lastName: 'Ali',
      fullName: 'Nour Ali',
      email: 'nour.ali@example.com',
      phoneNumber: '01522334455',
      photoUrl: 'https://cdn-icons-png.flaticon.com/128/16683/16683419.png',
      role: 'Admin',
      createdAt: '2024-07-01T12:00:00Z',
      isBlocked: false,
      isVerified: true,
    ),
    UserEntity(
      uid: 'u5',
      firstName: 'Mostafa',
      lastName: 'Youssef',
      fullName: 'Mostafa Youssef',
      email: 'mostafa.y@example.com',
      phoneNumber: '01011223344',
      photoUrl: 'https://cdn-icons-png.flaticon.com/128/16683/16683419.png',
      role: 'Guide',
      createdAt: '2024-07-10T18:00:00Z',
      isBlocked: true,
      isVerified: false,
    ),
  ];
}
