import 'package:in_egypt_admin_panel/core/Entities/BookingEntity.dart';
import 'package:in_egypt_admin_panel/core/Entities/PlaceEntity.dart';
import 'package:in_egypt_admin_panel/core/helpers/getUserData.dart';

class Variables {
  static List<BookingEntity> testBookingsList = [
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        imagesURLs: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        imagesURLs: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        imagesURLs: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      status: "approved",
      totalPrice: 100,
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        imagesURLs: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
    BookingEntity(
      id: "123551",
      user: getUserData(),
      createdAt: DateTime.now(),
      endAt: DateTime.now(),
      startAt: DateTime.now(),
      daysDuration: 2,
      numberOfGuests: 2,
      totalPrice: 100,
      status: "rejected",
      paymentMethod: "cash",
      place: PlaceEntity(
        id: "1215151253",
        location: "الجيزة",
        category: "تاريخية",
        name: "أهرامات الجيزة",
        description: "موقع مميز في الجيزة",
        imagesURLs: [],
        latitude: 124535,
        longitude: 125551,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        rating: 4.5,
        ticketPrice: 345,
      ),
    ),
  ];
  static List<PlaceEntity> testPlacesList = [
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
    PlaceEntity(
      id: "1215151253",
      location: "الجيزة",
      category: "تاريخية",
      name: "أهرامات الجيزة",
      description: "موقع مميز في الجيزة",
      imagesURLs: [],
      latitude: 124535,
      longitude: 125551,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      rating: 4.5,
      ticketPrice: 345,
    ),
  ];
}
